server:
  port: 8010
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myjava?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Zyt485129
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  data:
    redis:
      database: 2
      host: localhost
      port: 6379
      password:
  cache:
    redis:
      time-to-live: 60000
  mail:
    host: smtp.qq.com    #发送邮件服务器，请替换成自己的
    properties.mail.smtp.port: 465   #端口号
    username: amharuki@qq.com   #发送邮件的邮箱地址，请替换成自己的
    password: jqactvkbtoiyciec    #客户端授权码，不是邮箱密码，请替换成自己的
    #邮件服务超时时间配置
    properties.mail.smtp.connectiontimeout: 5000
    properties.mail.smtp.timeout: 3000
    properties.mail.smtp.writetimeout: 5000
    #ssl开启配置
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.debug: true
    default-encoding: utf-8    #邮件编码方式

mybatis-plus:
  type-aliases-package: com.hureru.design_v2.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

jwt:
  secret: f@6kxgxJ5$LFy$J2goBhsHr&u5dq&gbP
  expiration: 86400000